const express  = require('express');
const router   = express.Router();
const supabase = require('../config/db');
const PDFDocument = require('pdfkit');

// GET /api/corporates
router.get('/', async (req, res) => {
  const { data, error } = await supabase
    .from('corporates')
    .select('*')
    .order('company');
  if (error) return res.status(500).json({ error: error.message });
  res.json(data);
});

// POST /api/corporates
router.post('/', async (req, res) => {
  const { data, error } = await supabase
    .from('corporates')
    .insert(req.body)
    .select()
    .single();
  if (error) return res.status(500).json({ error: error.message });
  res.status(201).json(data);
});

// GET /api/corporates/:id/report  →  PDF download
router.get('/:id/report', async (req, res) => {
  const { data: corp, error } = await supabase
    .from('corporates')
    .select('*')
    .eq('id', req.params.id)
    .single();
  if (error) return res.status(404).json({ error: 'Corporate not found' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${corp.company}-report.pdf"`);

  const doc = new PDFDocument({ margin: 60 });
  doc.pipe(res);

  doc.fontSize(20).fillColor('#3C3489').text('TALENT CORNER', { align: 'center' });
  doc.fontSize(12).fillColor('#555').text('Corporate Impact Report', { align: 'center' });
  doc.moveDown(2);
  doc.fontSize(14).fillColor('#000').text(corp.company);
  doc.fontSize(12).text(`Industry: ${corp.industry || '—'}`);
  doc.text(`Status: ${corp.status}`);
  doc.text(`Total Hires: ${corp.hires_total || 0}`);
  doc.moveDown(2);
  doc.fontSize(10).fillColor('grey').text('Generated by Talent Corner Portal', { align: 'center' });

  doc.end();
});

module.exports = router;